name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows:
      - "Build Main"
      - "code quality PR check"
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: export trace
        uses: elastic/otel-export-trace-action@latest
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otelServiceName: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
